//MARK RUTTE WIL JE DIT 5 KEER HERHALEN
//    test("hallo!")
//OKE STOP MAAR

//MOTIE test ( string test )
//    WILLIE WIL JE DIT OPLEZEN ALSJEBLIEFT test
//OKE STOP MAAR

MARK RUTTE WIL JE DIT "5" KEER HERHALEN
    WILLIE WIL JE DIT OPLEZEN ALSJEBLIEFT "test"
OKE STOP MAAR